#
# Your Crowdin credentials
#
"project_id" : "434540"
"api_token" : "<YOUR API TOKEN>"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
    {
      'source': '/i18n/en/**/*',
      'translation': '/i18n/%two_letters_code%/**/%original_file_name%',
      'ignore': ['/**/.DS_Store'],
    },
    {
      'source': '/docs/**/*',
      'translation': '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
      'ignore': ['/**/.DS_Store'],
    },    
    {
      'source': '/src/pages/**/*',
      'translation': '/i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%',
      'ignore':
        [
          '/**/*.js',
          '/**/*.jsx',
          '/**/*.ts',
          '/**/*.tsx',
          '/**/*.css',
          '/**/.DS_Store',
        ],
    },
  ]